### ISSUE TITLE
Resolve double checks in CI, Linters and Coverage

### ISSUE THREAD

**Issue by destogl** [ros-controls/ros2_control_demos#16]
There is overlap in the tests when running CI, Linters and Coverage actions. It would be nice to resolve this at some point.

Ideas? Best practices?

**Comment by olivier-stasse** [comment]
Could you be a bit more specific ?

**Comment by destogl** [comment]
If you look at the actions it seams that the Lint-Tests are called in every configuration. This is probably because of `colcon test` call. I am not sure if this should/can be removed so that we have one specific action broken and all of them when some of the Lints are not happy.

**Comment by olivier-stasse** [comment]
It seems to come from 
https://github.com/ros-controls/ros2_control_demos/blob/fe783a869a8f5db0edbe7c954b19250b148f18a3/ros2_control_demo_robot/CMakeLists.txt#L26
for the ros2_control_demos package.
If it can be removed then it could set by a cmake option. Then the github action in charge of the linter would set it to TRUE.

**Comment by bmagyar** [comment]
Indeed that line breaks the build_and_test step when a linter fails which shouldn't really be the case as it goes against civilized CI setups where build, test and linting are separate stages. For technical reasons build and test cannot be separated and unfortunately due to the strange habit of linting being shoved into tests, it's all bundled up. 

I however support removing linting from the tests section in the cmake, the CI is set up to run linting steps separately already.

**Comment by destogl** [comment]
I will remove this line from CMakeLists.

**Comment by destogl** [comment]
I removed `lint` dependencies compleately in #18 .
